### ISSUE TITLE
[Bug] cachable-lookups requires builtin node modules that aren't present on esbuild in the browser

### ISSUE THREAD

**Issue by okikio** [ggoodman/esbuild-plugin-velcro#1]
When I try to use esbuild-velcro, it just errors out with this,

```bash
[21:35:18] Error in plugin "gulp-esbuild"
Message:
    Build failed with 21 errors:
node_modules/.pnpm/cacheable-lookup@5.0.4/node_modules/cacheable-lookup/source/index.js:10:12: error: Could not resolve "dns" (use "platform: 'node'" when building for node)
node_modules/.pnpm/cacheable-lookup@5.0.4/node_modules/cacheable-lookup/source/index.js:12:19: error: Could not resolve "os" (use "platform: 'node'" when building for node)
node_modules/.pnpm/decompress-response@6.0.0/node_modules/decompress-response/index.js:3:21: error: Could not resolve "zlib" (use "platform: 'node'" when building for node)
node_modules/.pnpm/esbuild-plugin-velcro@0.1.0_esbuild@0.12.1/node_modules/esbuild-plugin-velcro/dist/index.esm.js:6:20: error: Could not resolve "fs" (use "platform: 'node'" when building for node)
node_modules/.pnpm/esbuild-plugin-velcro@0.1.0_esbuild@0.12.1/node_modules/esbuild-plugin-velcro/dist/index.esm.js:8:19: error: Could not resolve "module" (use "platform: 'node'" when building for node)
```

**Comment by ggoodman** [comment]
Can you please share how you're instantiating `esbuild-plugin-velcro`?

In the README, [it suggests](https://github.com/ggoodman/esbuild-plugin-velcro#createpluginoptions) that you should configure `options.target: 'node'` to have node built-in modules shimmed.

**Comment by okikio** [comment]
Yeah I did that but it still gave me that error, also, can you use this velcro in the browser in esbuild-wasm?

**Comment by okikio** [comment]
Also, I forgot to mention yesterday but I also got this error,

```bash
import { createPlugin } from 'esbuild-plugin-velcro';
         ^^^^^^^^^^^^
SyntaxError: Named export 'createPlugin' not found. The requested module 'esbuild-plugin-velcro' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'esbuild-plugin-velcro';
const { createPlugin } = pkg;

```

even though I set my package.json to "type": "module".

And if I do this,

```js
import pkg from "esbuild-plugin-velcro";
const { createPlugin } = pkg;
```

I get this,

```bash
(node:4439) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/workspaces/bundle/node_modules/.pnpm/esbuild-plugin-velcro@0.1.0_esbuild@0.12.1/node_modules/esbuild-plugin-velcro/dist/index.esm.js:1
import { CdnStrategy } from '@velcro/strategy-cdn';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:192:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
```

**Comment by ggoodman** [comment]
Hi @okikio, I'm in the process of fixing up the "exports" map. I suspect that's what's giving you issues using `esbuild-plugin-velcro`.

> can you use this velcro in the browser in esbuild-wasm?

While velcro itself is designed to work as well in the browser as in Node, this plugin doesn't support that in its current state. To support running in the browser, a couple small changes would be required as well as adding options for you to supply a custom 'mock fs' and 'read url function'. The former is needed to support resolving dependencies (ie: finding and reading your `package.json` file) while the latter would need to replace the module's current [`got`](https://npm.im/got)-based http client.

Can you tell me a little bit about your use-case?

**Comment by ggoodman** [comment]
@okikio can you tell me if `0.1.1` fixes the import issue for your?

**Comment by okikio** [comment]
I am creating an online bundler based on esbuild, but as of right now my bundler sometimes runs into edge cases where one CDN is better than the other at grabbing specific packages, I was hoping your package would be able to remove this bug.

You can check out the online bundler here, [okikio.github.io/bundle](https://okikio.github.io/bundle)

**Comment by okikio** [comment]
@ggoodman the update doesn't seem to have been pushed to npm, also, I created a pull request #2 that should also fix some bugs.

**Comment by okikio** [comment]
I would also suggest giving the user the ability to choose their own version of the fs library that they want to use, I currently use `memfs` for emulating `fs`, and `fetch` for `got` (`got` relies on builtin modules like http).

**Comment by okikio** [comment]
Also, would it be possible to fore go the package.json requirement, my bundler works just by seeing what packages are in a file and attaches the package name to `unpkg.com`

**Comment by okikio** [comment]
@ggoodman I have now recieved the update, but I still get this error,

```bash

(node:534) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/workspaces/bundle/node_modules/.pnpm/esbuild-plugin-velcro@0.1.1_esbuild@0.12.1/node_modules/esbuild-plugin-velcro/dist/index.esm.js:1
import { CdnStrategy } from '@velcro/strategy-cdn';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

I think you have to rename the .esm.js file to .mjs, you might have to update you rollup build task

I have updated pull request #2 to rename the .esm.js file to .mjs

**Comment by ggoodman** [comment]
@okikio, can you take a look at #3 and let me know what you think?

**Comment by okikio** [comment]
It looks awesome, I'll have to test it out locally to make sure it works fully but it looks good. I'd suggest merging pull request #2  before publishing to npm.

**Comment by okikio** [comment]
@ggoodman I tried it out here are the results. 

For browsers, you should specify that the cwd is required I didn't know that, and I expected it to just use memfs but it doesn't, and also, enable users to not need a package.json, its a little inconvenient to setup on a browser.

My setup looks like this,

```ts
import { initialize, build } from "esbuild-wasm/esm/browser";
import path from "path";
import { fs, vol } from "memfs";

import { EXTERNAL} from "../plugins/external";
import { ENTRY } from "../plugins/entry";
import { VIRTUAL_FS } from "../plugins/virtual-fs";

import { createBrowserPlugin } from "../plugins/velcro";
import { FsStrategy } from "@velcro/strategy-fs";

import prettyBytes from "pretty-bytes";
import { gzip } from "pako";

export let _initialized = false;
export const init = async () => {
    try {
        // Check if esbuild is initialized
        if (!_initialized) {
            await initialize({
                worker: true,
                wasmURL: `./js/esbuild.wasm`
            });

            _initialized = true;
        }
    } catch (e) {
        console.warn("esbuild initialize error", e);
        return "Error";
    }
}

vol.fromJSON({
    "./package.json": JSON.stringify({
        "dependencies": {
            "@babel/core": "*"
        }
    })
}, "/")

export const size = async (input: string) => {
    input = `${input}`; // Ensure input is string
    if (!_initialized) return "Error";

    let content: string;

    try {
        await fs.promises.writeFile("input.ts", `${input}`);

        let result = await build({
            entryPoints: ['<stdin>'],
            bundle: true,
            minify: true,
            color: true,
            incremental: true,
            target: ["es2020"],
            logLevel: 'info',
            write: false,
            outfile: "/bundle.js",
            platform: "browser",
            format: "esm",
            define: {
                "__NODE__": `false`,
                "process.env.NODE_ENV": `"production"`
            },
            plugins: [
                EXTERNAL(),
                ENTRY(`/input.ts`),

                createBrowserPlugin({
                    cwd: "/",
                    fs: fs as FsStrategy.FsInterface
                }),

                VIRTUAL_FS()
            ],
            globalName: 'bundler',
        });

        result?.outputFiles?.forEach((x) => {
            if (!fs.existsSync(path.dirname(x.path))) {
                fs.mkdirSync(path.dirname(x.path));
            }

            fs.writeFileSync(x.path, x.text);
        });

        content = await fs.promises.readFile("/bundle.js", "utf-8") as string;
        content = content?.trim?.(); // Remove unesscary space

        // Reset memfs
        vol.reset();
    } catch (e) {
        console.warn(`esbuild build error`, e);
        return "Error";
    }

    try {
        let { length } = gzip(content, { level: 9 });
        let size = prettyBytes(length);

        console.groupCollapsed(`${size} => Bundled Code: `);
        console.log(content);
        console.groupEnd();

        return size;
    } catch (e) {
        console.warn("Error zipping file ", e);
        return "Error";
    }
};
```

I entered this into the input, 

```ts
export * from "@babel/core";
```

The results are following the console errors,

```bash
 > velcro:https://cdn.jsdelivr.net/npm/debug@4.3.2/src/node.js:32:31: error: [plugin: velcro] Unable to resolve 'The dependency 'supports-color' of 'https://cdn.jsdelivr.net/npm/debug@4.3.2/src/node.js' was not found'
    32 │   const supportsColor = require('supports-color');
       ╵                                 ~~~~~~~~~~~~~~~~

50cf62cd-8c2d-4a47-91df-c9ed3dde1d29:663  > velcro:https://cdn.jsdelivr.net/npm/@babel/core@7.14.3/lib/config/helpers/config-api.js:20:16: error: [plugin: velcro] Detected a recursive call to the operation 'resolveAsFile' for 'https://cdn.jsdelivr.net/npm/@babel/core@7.14.3/lib/' at path 'resolve(https) -> resolveUri(https) -> resolveAsFile(https) -> resolveAsDirectory(https)'
    20 │ var _ = require("../../");
       ╵                 ~~~~~~~~

50cf62cd-8c2d-4a47-91df-c9ed3dde1d29:663 2 errors
esbuild.min.js:788 esbuild build error Error: Build failed with 2 errors:
velcro:https://cdn.jsdelivr.net/npm/@babel/core@7.14.3/lib/config/helpers/config-api.js:20:16: error: [plugin: velcro] Detected a recursive call to the operation 'resolveAsFile' for 'https://cdn.jsdelivr.net/npm/@babel/core@7.14.3/lib/' at path 'resolve(https) -> resolveUri(https) -> resolveAsFile(https) -> resolveAsDirectory(https)'
velcro:https://cdn.jsdelivr.net/npm/debug@4.3.2/src/node.js:32:31: error: [plugin: velcro] Unable to resolve 'The dependency 'supports-color' of 'https://cdn.jsdelivr.net/npm/debug@4.3.2/src/node.js' was not found'
    at Qn (esbuild.min.js:84)
    at esbuild.min.js:77
    at Q (esbuild.min.js:77)
    at xr (esbuild.min.js:77)
    at esbuild.min.js:77
    at esbuild.min.js:77
    at x (esbuild.min.js:77)
    at h (esbuild.min.js:77)
    at Worker.o.onmessage (esbuild.min.js:784)
```

If I use my previous setup with these custom made plugins,

```ts
import { EXTERNAL } from "../plugins/external";
import { ENTRY } from "../plugins/entry";
import { JSON_PLUGIN } from "../plugins/json";
import { BARE } from "../plugins/bare";
import { HTTP } from "../plugins/http";
import { CDN } from "../plugins/cdn";
import { VIRTUAL_FS } from "../plugins/virtual-fs";
import { WASM } from "../plugins/wasm";
// ...
await build({
    // ...
    plugins: [
            EXTERNAL(),
            ENTRY(`/input.ts`),
            JSON_PLUGIN(),
            
            HTTP(),
            BARE(),
            CDN(),
            VIRTUAL_FS(),
            WASM()
    ],
    // ...
})
```

I only get this error,

```ts
 > cdn:../../:1:0: error: Unexpected "<"
    1 │ <!DOCTYPE html><html lang="en"><head><script async="" src="https://ww...
      ╵ ^

6a82f80a-f7f0-4fc6-9b09-5fa3f49318de:663 1 error
esbuild.min.js:794 esbuild build error Error: Build failed with 1 error:
cdn:../../:1:0: error: Unexpected "<"
    at ei (esbuild.min.js:84)
    at esbuild.min.js:77
    at Q (esbuild.min.js:77)
    at Ir (esbuild.min.js:77)
    at esbuild.min.js:77
    at esbuild.min.js:77
    at x (esbuild.min.js:77)
    at h (esbuild.min.js:77)
    at Worker.o.onmessage (esbuild.min.js:784)
```

After doing some research I found that this leads to [https://unpkg.com/@babel/core@7.14.3/lib/](https://unpkg.com/@babel/core@7.14.3/lib/)

This is an easy fix just replace / with /index.html, but I am worried by fixing this I wouldn't be applying the commonjs module algorithm properly.

_**Note**: the custom plugins are located here [github.com/okikio/bundle/tree/main/src/ts/plugins](https://github.com/okikio/bundle/tree/main/src/ts/plugins) and the actual esbuild task is here [github.com/okikio/bundle/blob/main/src/ts/modules/esbuild.ts](https://github.com/okikio/bundle/blob/main/src/ts/modules/esbuild.ts), also, they don't require a package.json to work, so please add support for not needing a package.json_

**Comment by okikio** [comment]
@ggoodman are you still able to work on the updates to velcro?

**Comment by ggoodman** [comment]
Hi @okikio, I'm not using this in production in any capacity at the moment. Would you like to have write access to this repo so that you can unblock yourself?

I'm happy to try to address bugs in Velcro itself but might find it tough to dedicate time to this particular plugin.

**Comment by okikio** [comment]
Sure, I'll push changes and try to fix any bugs I find
